### ISSUE TITLE
Elaboração inicial RoadMap

### ISSUE THREAD

**Issue by NilvanPeres** [fga-eps-mds/2020.2-CheeryUP#25]
### Descrição:
Estudar e escolher um modelo inicial para elaboração inicial do RoadMaps do projeto.

### Tarefas:

- [x] Estudar e escolher uma estrutura de RoadMap para ScrumMaster/ProductOwner/DevOps/DevTeam

- [x] Criação do documento RoadMap ScrumMaster.

- [x] Criação do documento RoadMap ProductOwner.

- [x] Criação do documento RoadMap DevOps.

- [x] Criação do documento RoadMap DevTeam.

### Critérios de aceitação:

* Cada um deve preencher o documento conforme sua função no projeto, todos devem contribuir.
* Revisão ortográfica do documento.

**Comment by DaviMatheus** [comment]
não se esquecem de dar uma olhada [nisso](https://github.com/fga-eps-mds/MDS-2020-2-G7/issues/14#issuecomment-780765659) @Abraao1231 @antoniotoineto @art1505 @fernandes-natanael

**Comment by antoniotoineto** [comment]
Fala rapaziada 😃 👍  

Encontrei um vídeo bem curtinho, para uma ideia inicial do RoadMap. [Clique aqui](https://www.youtube.com/watch?v=o4dakb2yatE) para acessá-lo.
Também há um vídeo mais longo para uma ideia mais aprofundada. [Clique aqui](https://www.youtube.com/watch?v=hVwRwrvL7fg).
[Nesse site](https://pt.venngage.com/blog/roadmap-de-produto/) apresenta alguns templates de RoadMap, caso queiramos usar algum modelo pronto.

@juninhigh @DaviMatheus @fernandes-natanael @art1505 @Abraao1231

**Comment by DaviMatheus** [comment]
Estaremos utilizando o [Figma](https://www.figma.com/) para criar os fluxogramas para o roadmap

**Comment by fernandes-natanael** [comment]
Galera esse aqui será o template temporário para criação de roadmaps. Para pegarem o template usem este link de acesso: [Template Figma ]( https://www.figma.com/proto/FSWkfMPRHHuIy4wu5FVBo1/Untitled?node-id=1%3A2&scaling=min-zoom) 

![Template_roadmap](https://user-images.githubusercontent.com/56640659/109097436-128e0480-76fe-11eb-9c02-da714e0ba90c.png)

**Comment by NilvanPeres** [comment]
Pessoal o documento ScrumMaster foi adicionado conforme o planejado. Dev Team e DevOps @Abraao1231  @fernandes-natanael @antoniotoineto @art1505 não se esqueçam de adicionar o Figma nos documentos.

**Comment by fernandes-natanael** [comment]
Organizei no figma de modo que todos os documentos fique disponíveis para que possam alterar sempre que houver alguma mudança, segue o link: [https://www.figma.com/file/FSWkfMPRHHuIy4wu5FVBo1/Untitled?node-id=0%3A1](https://www.figma.com/file/FSWkfMPRHHuIy4wu5FVBo1/Untitled?node-id=0%3A1)


@juninhigh @antoniotoineto @DaviMatheus @Abraao1231

**Comment by DaviMatheus** [comment]
Terminado o RoadMap do [DevTeam](https://github.com/fga-eps-mds/MDS-2020-2-G7/blob/main/docs/Roadmaps/roadmap_DevTeam.md) lembrando que esse documento precisa ser atualizado constantemente para não acumular
