### ISSUE TITLE
Docs Sprint 05 e ATA 

### ISSUE THREAD

**Issue by art1505** [fga-eps-mds/2020.2-CheeryUP#64]
### Descrição:
Criar documentação da Sprint 05.
### Tarefas:

- [x] Adicionar o planning da sprint.
- [x] Adicionar a review da sprint.
- [x] Adicionar a ATA de reuniões da Sprint 05.

### Critério de aceitação:
- O planning deve ter boa descrição do que deve ser seguido ao longo da sprint.
- A review deve ter o relato do ScrumMaster e BurnDown Chart.
- A ATA de reuniões deve seguir o seguinte modelo:

## ATA

|Nome_Ata | About |
| :- | :- |
| - |  -  |

| Data  | Local | Horário  | Duração | Autor | Semanal/Daily | Participantes |
| :- | :- | :- | :- | :- | :- | :- |
|  x | Jitsi | 18h | -- |  -- | -- | -- ||

***Pontos planejado***  

1.  

2.  

3.  

4. 

***Assuntos pendentes***
* Atraso de funcionalidade X, resolvido.

***Tasks e responsáveis***
- [] Issue x, @assignerY
