### ISSUE TITLE
Docs Sprint 8 e ATA

### ISSUE THREAD

**Issue by DaviMatheus** [fga-eps-mds/2020.2-CheeryUP#88]
### Descrição:
Criar documentação da Sprint 08
### Tarefas:

- [x] Adicionar o planning da sprint.
- [x] Adicionar a review da sprint.
- [x] Adicionar a ATA de reuniões da Sprint 08.

### Critério de aceitação:
- O planning deve ter boa descrição do que deve ser seguido ao longo da sprint.
- A review deve ter o relato do ScrumMaster e BurnDown Chart.
- A ATA de reuniões deve seguir o seguinte modelo:

## ATA

|Nome_Ata | About |
| :- | :- |
| - |  -  |

| Data  | Local | Horário  | Duração | Autor | Semanal/Daily | Participantes |
| :- | :- | :- | :- | :- | :- | :- |
|  x | Jitsi | 18h | -- |  -- | -- | -- ||

***Pontos planejado***  

1.  

2.  

3.  

4. 

***Assuntos pendentes***
* Atraso de funcionalidade X, resolvido.

***Tasks e responsáveis***
- [] Issue x, @assignerY

**Comment by art1505** [comment]
Mais tarde, serão feitas as devidas alterações por meio da adição do time box da sprint e, eventualmente, modificações no quadro de histórias da mesma. 👍

**Comment by DaviMatheus** [comment]
Adicionada as Atas da Sprint 7 que estavam atrasada e das reuniões feitas da sprint 8 até hoje, nas quais são muito importante devido a issue #91, no caso que estamos procurando criar uma conexão com nosso clientes. 🤓 👍

**Comment by DaviMatheus** [comment]
Adicionadas todas as ATAS das reuniçoes da Sprint 8, no quais foram muitas devido as reuniões com as psicólogas ( citadas na issue #91) e a reunião com a professora onde ela deu um feedback mais especifico em relação ao nosso grupo, em que para quem não pode vir os detalhas da reunião pode ser visto [aqui](https://github.com/fga-eps-mds/2020.2-CheeryUP/blob/main/docs/AtaReunioes/Ata%20de%20Reuni%C3%B5es%2008/Reuni%C3%A3o_06.md). Agora só vai a review da Sprint para podermos fechar nossa issue @NilvanPeres.
